# Generated by Django 4.0.5 on 2023-06-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_remove_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
