# Generated by Django 4.0.5 on 2023-06-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0011_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
